### ISSUE TITLE
F811 (redefinition of unused variable) incorrectly triggered with @overload decorator

### ISSUE THREAD

**Issue by bartvm** [PyCQA/pyflakes#320]
PEP 484 [introduced](https://www.python.org/dev/peps/pep-0484/#function-method-overloading) the `@overload` decorator for type annotations.

> [...] a series of `@overload`-decorated definitions must be followed by exactly one non-@overload-decorated definition (for the same function/method). The `@overload`-decorated definitions are for the benefit of the type checker only, since they will be overwritten by the non-`@overload`-decorated definition, while the latter is used at runtime but should be ignored by a type checker.

The following should pass PyFlakes without errors, but currently triggers F811 errors:

```python
from typing import overload


@overload
def utf8(value: None) -> None:
    pass


@overload
def utf8(value: bytes) -> bytes:
    pass


@overload
def utf8(value: str) -> bytes:
    pass


def utf8(value):
    pass  # actual implementation
```
```
test.py:9:1: F811 redefinition of unused 'utf8' from line 4
test.py:14:1: F811 redefinition of unused 'utf8' from line 9
test.py:19:1: F811 redefinition of unused 'utf8' from line 14
```

**Comment by tscholak** [comment]
facing the same issue. do you have a workaround?

**Comment by bartvm** [comment]
Added this to `. pydocstyle`
```
[pydocstyle]
ignore-decorators = overload
```

**Comment by sigmavirus24** [comment]
How does pydocstyle config fix a pyflakes bug?

**Comment by asottile** [comment]
I took a stab at this: https://github.com/PyCQA/pyflakes/pull/371

**Comment by feisuzhu** [comment]
Hi, it's good to see https://github.com/PyCQA/pyflakes/pull/371 been solved, but `overload`s on class is still incorrectly triggered

```python
import typing
from typing import overload


class Foo:
    @overload
    def f(self, s):  # type: (None) -> None
        pass


    @overload
    def f(self, s):  # type: (int) -> int
        pass


    def f(self, s):
        return s


    @typing.overload
    def g(self, s):  # type: (None) -> None
        pass


    @typing.overload
    def g(self, s):  # type: (int) -> int
        pass


    def g(self, s):
        return s
```

```
☁  shm  pyflakes a.py 
a.py:11: redefinition of unused 'f' from line 6
a.py:16: redefinition of unused 'f' from line 11
☁  shm  pyflakes --version
2.1.1 Python 3.6.7 on Linux
```

**Comment by asottile** [comment]
@feisuzhu try master, I've already fixed this: https://github.com/PyCQA/pyflakes/pull/435

**Comment by eellison** [comment]
I still have this issue when the overload decorator is wrapped by another decorator.

```
def my_decorator(func):
    return typing.overload(func)

@my_decorator
def utf8(value: None) -> None:
    pass

@my_decorator
def utf8(value: bytes) -> bytes:
    pass

def utf8(value):
    pass  # actual implementation
```

**Comment by asottile** [comment]
that's not possible to detect statically -- I'd suggest not doing that (I don't think mypy can detect that either)

I'd suggest explicitly using the overload decorator

**Comment by eellison** [comment]
Gotcha. This doesn't work either fwiw.

```
from typing import overload

def my_decorator(func):
    return func

@overload
@my_decorator
def utf8(value: None) -> None:
    pass

@overload
@my_decorator
def utf8(value: bytes) -> bytes:
    pass

def utf8(value):
    pass  # actual implementation

```

**Comment by asottile** [comment]
Have you tried on master? it works for me

**Comment by asottile** [comment]
actually, it even works with the released version of pyflakes so you're probably on an old one

**Comment by eellison** [comment]
This is my version info that doesn't work:

```3.7.8 (flake8-comprehensions: 2.1.0, flake8-mypy: 17.8.0, mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.6.8 on Linux```

What do you think about counting a decorator as a use of a function?

**Comment by asottile** [comment]
actually, I'm wrong about it being already released -- it is fixed on master though, please try that and confirm

**Comment by asottile** [comment]
see #435

**Comment by eellison** [comment]
yea works on master, thanks!
